#!/usr/bin/env node
/**
 * Concatenates modular panel CSS into a single public/css/panel.css with no @import.
 * Source of truth: sibling modules under public/css/. Run via `npm run build:css`.
 */
const fs = process.getBuiltinModule('fs');
const path = process.getBuiltinModule('path');

const cssDir = path.join(import.meta.dirname, '..', 'public', 'css');
const outFile = path.join(cssDir, 'panel.css');

/** Fixed order matching the former panel.css @import list. */
const MODULES = [
  'tokens.css',
  'layout.css',
  'nav.css',
  'primitives.css',
  'auth.css',
  'inventory.css',
  'manage.css',
  'feedback.css',
  'utilities.css',
  'responsive.css',
];

const BANNER = `/* Generated by scripts/build-css.mjs — do not edit panel.css directly.
   Edit public/css/*.css modules, then run npm run build:css.
   Entry selectors .auth-page and .panel are defined in the modules below. */
`;

function loadModule(name) {
  const filePath = path.join(cssDir, name);
  if (!fs.existsSync(filePath)) {
    throw new Error(`CSS module missing: ${filePath}`);
  }
  const body = fs.readFileSync(filePath, 'utf8').replace(/\r\n/g, '\n').replace(/\s+$/, '') + '\n';
  return `/* === ${name} === */\n${body}`;
}

const parts = [BANNER];
for (const name of MODULES) {
  parts.push(loadModule(name));
}

const output = `${parts.join('\n')}`;
fs.writeFileSync(outFile, output, 'utf8');

const rel = path.relative(process.cwd(), outFile);
console.log(`Wrote ${rel} (${Buffer.byteLength(output, 'utf8')} bytes, ${MODULES.length} modules)`);
